version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "redshift-migration-agent"
resolve_s3 = true
s3_prefix = "redshift-migration-agent"
region = "us-east-2"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "BedrockModelId=us.anthropic.claude-sonnet-4-5-20250929-v1:0 FunctionMemorySize=2048 FunctionTimeout=300"
image_repositories = []

[default.build]
[default.build.parameters]
cached = true
parallel = true
